### ISSUE TITLE
Step fails for 1.0.4

### ISSUE THREAD

**Issue by oprearobert** [guitcastro/steps-update-sdk#11]
Recently, the builds on bitrise have started to fail on this. It is not specified exactly what the problem is, but I've noticed something strange in the logs, specifically:

updating sdk using filter = "platform-tools" "android;14" "android;16" "build-tools;23.0.1" "extra-google-google_play_services" "extra-google-m2repository" "extra-android-m2repository" "addon-google_apis-google-17" "addon-google_apis-google-23" "sys-img-armeabi-v7a-android-23" "sys-img-x86-android-23"

I've looked into the script file and notice that for the FILTER we are appending ; instead of - at the end. This also leads to another warning before the step fails:

Warning: Failed to find package android;14

Shouldn't the FILTER be android-14, instead of android;14?

**Comment by guitcastro** [comment]
it's seems that now, we have to add the `platforms;` prefix and use `-` as pointed you pointed out. 
So the correct filter would be: `"platforms;android-14"` and so on ...

I will work on a fix and try to publish tonight.

Thanks for the report

**Comment by guitcastro** [comment]
Another think, you have to update the others extras to meet the new name convention:

`extra-google-google_play_services` -> `extras;google;googlee_play_services`
`extra-google-m2repository` -> ` extras;google;m2repository`
`extra-android-m2repository` -> `extras;android;m2repository`
`addon-google_apis-google-17` -> `add-ons;addon-google_apis-google-15`
`sys-img-armeabi-v7a-android-23` -> `system-images;android-23;default;armeabi-v7a`
`sys-img-x86-android-23` -> `system-images;android-23;default;x86`

**Comment by razanbilwani** [comment]
Thanks @guitcastro! We did 😄

**Comment by guitcastro** [comment]
Done, We just need to wait the guys from bitrise to approve the PR. The working versions is the 1.0.6.
