### ISSUE TITLE
Add ons

### ISSUE THREAD

**Issue by hijklmno** [guitcastro/steps-update-sdk#7]
Hi,

Thanks for the step! 

I have a corner case where I needed to install the GDK as well. In order to download it, I must run 
`android update sdk --no-ui --filter "add-on"` (which does not filter down correctly, i noticed). I have solved the problem but putting "add-on" as a variable in systemImages, because I noticed in your step.sh that you're passing that directly into the filter without appending any strings.

If someone were to add a add-on, how would they go about doing so? Also, how would the android perform a more granular filtering of all the add-ons?

Thanks!

**Comment by guitcastro** [comment]
@hijklmno did fix the issue?

**Comment by guitcastro** [comment]
@hijklmno  I don't know if you solved your issue. I have to add a field for addon as well, in the main time you can use the systemimages.

You can check all available addons using this command:

`android list sdk -a -e | grep addon`

Here is the output:

```
id: 109 or "addon-google_apis-google-23"
id: 110 or "addon-google_apis-google-22"
id: 111 or "addon-google_apis-google-21"
id: 112 or "addon-google_apis_x86-google-19"
id: 113 or "addon-google_apis-google-19"
id: 114 or "addon-google_gdk-google-19"
id: 115 or "addon-google_apis-google-18"
id: 116 or "addon-google_apis-google-17"
id: 117 or "addon-google_apis-google-16"
id: 118 or "addon-google_apis-google-15"
id: 119 or "addon-google_apis-google-14"
id: 120 or "addon-google_apis-google-13"
id: 121 or "addon-google_tv_addon-google-13"
id: 122 or "addon-google_apis-google-12"
id: 123 or "addon-google_apis-google-11"
id: 124 or "addon-google_apis-google-10"
id: 125 or "addon-google_apis-google-9"
id: 126 or "addon-google_apis-google-8"
id: 127 or "addon-google_apis-google-7"
id: 128 or "addon-google_apis-google-6"
id: 129 or "addon-google_apis-google-5"
id: 130 or "addon-google_apis-google-4"
id: 131 or "addon-google_apis-google-3"
id: 132 or "sys-img-armeabi-v7a-addon-google_apis-google-23"
id: 133 or "sys-img-x86_64-addon-google_apis-google-23"
id: 134 or "sys-img-x86-addon-google_apis-google-23"
id: 135 or "sys-img-armeabi-v7a-addon-google_apis-google-22"
id: 136 or "sys-img-x86_64-addon-google_apis-google-22"
id: 137 or "sys-img-x86-addon-google_apis-google-22"
id: 138 or "sys-img-armeabi-v7a-addon-google_apis-google-21"
id: 139 or "sys-img-x86_64-addon-google_apis-google-21"
id: 140 or "sys-img-x86-addon-google_apis-google-21"
```

You can use the `addon-google_apis-google-13` per example

**Comment by hijklmno** [comment]
Hi @guitcastro, the issue was fixed via putting `addon-google_gdk-google-19` into the systemImages variable, per your suggestion. I was passing `add-on` before but it downloaded all the add-ons that were unnecessary. Your suggestion works. Thanks!
