### ISSUE TITLE
android-sdk-update | Bitrise build error

### ISSUE THREAD

**Issue by mxpmd03** [guitcastro/steps-update-sdk#8]
Latest commit is creating build errors. Following is the snapshot.

------------------------------------------------------------------------------+
| (0) android-sdk-update                                                       |
+------------------------------------------------------------------------------+
| id: android-sdk-update                                                       |
| version: 1.0.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-03-20T01:07:07-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise164328372/step_src/step.sh: line 47: /Users/guilherme/Library/Android/sdk/tools/bin/sdkmanager: No such file or directory
Local Support library repository not found
updating sdk using filter = "tools" "platform-tools" "android;23" "build-tools;23.0.3" "extras;android;m2repository"
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise164328372/step_src/step.sh: line 197: /Users/guilherme/Library/Android/sdk/tools/bin/sdkmanager: No such file or directory
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | android-sdk-update (exit code: 1)                             | 11 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/guitcastro/steps-update-sdk/issues         |
| Source: https://github.com/guitcastro/steps-update-sdk                       |
+---+---------------------------------------------------------------+----------+

**Comment by cjgehinscott** [comment]
Any updates on whether this will be fixed? I'm seeing the same issue for 25.0.0

**Comment by guitcastro** [comment]
I Just release it, sorry guys I totally forgot about. 
Now we just have to wait them to accept the PR.

Thanks for the feedback.
